### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [DylanDelobel/agnoster-timestamp-newline-zsh-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one

**Comment by DylanDelobel** [comment]
Glad to be listed! Done in 569cf2a6acc476b2dc50c2f22f630be26d4cf06f

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/676, thanks!
